presentation-grading/config/routes.rb
Rails.application.routes.draw do
  get 'classrooms_controller/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :classrooms, only: [:index, :show] do
    resources :presentations, only: [] do
      resources :grade_submissions, only: [:new, :create]
    end
  end

  root to: "classrooms#index"
end

presentation-grading/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

presentation-grading/app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_many :presentations, dependent: :destroy

  scope :current, -> { where(current: true) }
end

presentation-grading/app/models/grade_submission.rb
class GradeSubmission < ActiveRecord::Base
  validates(
    :email,
    :appropriate_length,
    :design_pattern,
    :good_description,
    :good_support,
    :bad_description,
    :bad_support,
    :improvement,
    :good_agree,
    :bad_agree,
    presence: true)

  validates(
    :appropriate_length,
    :design_pattern,
    :good_description,
    :good_support,
    :bad_description,
    :bad_support,
    :improvement,
    :good_agree,
    :bad_agree,
    inclusion: { in: (1..10).to_a })

  validates :email, uniqueness: { scope: :presentation_id }

  belongs_to :presentation
end

presentation-grading/app/models/presentation.rb
class Presentation < ActiveRecord::Base
  DATE_CHOICES = {
    '5/5' => '05/May/2015'.to_date,
    '5/7' => '07/May/2015'.to_date,
    '5/12' => '12/May/2015'.to_date
  }
  DATES = [
    '05/May/2015'.to_date,
    '07/May/2015'.to_date,
    '12/May/2015'.to_date
  ]

  belongs_to :classroom

  validates :date, :presenter_name, :topics, presence: true
  validates :date, inclusion: { in: DATES }
  validate :classroom_presence

  has_many :grade_submissions

  def grade_count
    grade_submissions.count
  end

  private

  def classroom_presence
    errors.add(:classroom_id, "can't be blank") unless self.classroom_id
  end
end

presentation-grading/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

presentation-grading/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.current
  end

  def show
    @classroom = Classroom.find(params[:id])
    @presentations = Presentation.where(classroom_id: @classroom.id)
    if params[:date]
      @presentations = @presentations.where(date: params[:date])
    end
  end
end

presentation-grading/app/controllers/grade_submissions_controller.rb
class GradeSubmissionsController < ApplicationController
  before_action :set_classroom_and_presentation, only: [:new, :create]

  def new
    @grade_submission = GradeSubmission.new(presentation: @presentation)
  end

  def create
    @grade_submission = GradeSubmission.new(grade_submission_params)
    @grade_submission.presentation = @presentation
    if @grade_submission.save
      flash[:notice] = "Grade for #{@grade_submission.presentation.presenter_name} successfully submitted. Thank you!"
      redirect_to classroom_path(@grade_submission.presentation.classroom)
    else
      render :new
    end
  end

  private

  def grade_submission_params
    params.require(:grade_submission).permit(
      :email,
      :appropriate_length,
      :design_pattern,
      :good_description,
      :good_support,
      :bad_description,
      :bad_support,
      :improvement,
      :good_agree,
      :bad_agree,
      :comments,
      :presentation_id)
  end

  def set_classroom_and_presentation
    @classroom = Classroom.find params[:classroom_id]
    @presentation = Presentation.find params[:presentation_id]
  end
end

presentation-grading/app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
end

presentation-grading/app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(resource, field)
    errors = resource.errors[field]
    if errors.any?
      "<div class='row padding'><span class='bg-danger padding'>#{errors.first}</span></div>".html_safe
    end
  end
end

presentation-grading/app/helpers/classrooms_controller_helper.rb
module ClassroomsControllerHelper
end

presentation-grading/app/helpers/grade_submissions_helper.rb
module GradeSubmissionsHelper
end

presentation-grading/app/helpers/presentation_controller_helper.rb
module PresentationControllerHelper
end

presentation-grading/app/views/classrooms/index.html.erb
<div class="col-xs-12 col-xs-offset-0 col-md-6 col-md-offset-3">
  <h1>Choose Your Class</h1>
  <% @classrooms.each do |classroom| %>
    <%= link_to classroom.name, classroom_path(classroom), class: 'btn btn-primary btn-large' %>
  <% end %>
</div>

presentation-grading/app/views/classrooms/show.html.erb
<div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
  <h1><%= @classroom.name %></h1>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <td>Presentation Date</td>
        <td>Student Name</td>
        <td>Website Topics</td>
        <td>Submit a Grade</td>
      </tr>
    </thead>
    <tbody>
      <% @classroom.presentations.each do |presentation| %>   
        <tr>
          <td><%= presentation.date %></td>
          <td><%= presentation.presenter_name %></td>
          <td><%= presentation.topics %></td>
          <td><%= link_to 'Grade', new_classroom_presentation_grade_submission_path(@classroom.id, presentation.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

presentation-grading/app/views/grade_submissions/new.html.erb
<div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
  <div class="jumbotron">
  <h3>Currently Grading:<h3>
  <h2>
    <%= @presentation.presenter_name %>'s Presentation on <%= @presentation.topics %>
  </h2>
  <h3>(All fields except Comments are required)</h3>
  <h3>1 = Awful, 10 = Fantastic</h3>
  </div>
  <%= form_for @grade_submission, url: classroom_presentation_grade_submissions_path(@classroom, @presentation) do |f| %>
    <div class="form-group">
      <%= f.label :email, 'Your email?' %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= errors_for(@grade_submission, :email) %>
    </div>
    <div class="form-group">
      <%= f.label :good_description, 'Was the website with <span class="text-success">good UI</span> described well?<br>(1 = Not at all, 10 = Extremely well)'.html_safe %>
      <br>
      <%= errors_for @grade_submission, :good_description %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[good_description]" class="radio-inline">
        <%= f.radio_button :good_description, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :good_support, 'Did the presenter provide good supporting reasons for why the website\'s UI was <span class="text text-success">good</span>?<br>(1 = Not at all, 10 = Yes, plenty, and they all made sense)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :good_support) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[good_support]" class="radio-inline">
        <%= f.radio_button :good_support, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :good_agree, 'Do you agree that the presenter\'s example of a website with <span class="text text-success">good UI</span> indeed has a <span class="text text-success">good user interface</span>?<br>(1 = I completely disagree, 10 = I agree 110%)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :good_agree) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[good_agree]" class="radio-inline">
        <%= f.radio_button :good_agree, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :bad_description, 'Was the website with <span class="text-danger">bad UI</span> described well?<br>(1 = Not at all, 10 = Extremely well)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :bad_description) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[bad_description]" class="radio-inline">
        <%= f.radio_button :bad_description, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :bad_support, 'Did the presenter provide good supporting reasons for why the website\'s UI was <span class="text text-danger">bad</span>?<br>(1 = Not at all, 10 = Yes, plenty, and they all made sense)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :bad_support) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[bad_support]" class="radio-inline">
        <%= f.radio_button :bad_support, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :bad_agree, 'Do you agree that the presenter\'s example of a website with <span class="text text-danger">bad UI</span> indeed has a <span class="text text-danger">bad user interface</span>?<br>(1 = I completely disagree, 10 = I agree 110%)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :bad_agree) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[bad_agree]" class="radio-inline">
        <%= f.radio_button :bad_agree, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :improvement, 'Did the presenter give examples of ways to improve on the website with <span class="text text-danger">bad UI</span>?<br>(1 = I completely disagree, 10 = I agree 110%)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :improvement) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[improvement]" class="radio-inline">
        <%= f.radio_button :improvement, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :design_pattern, 'Did the presentation give two examples of design patterns used in each websites?<br>(1 = None, 10 = Two for each website)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :design_pattern) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[design_pattern]" class="radio-inline">
        <%= f.radio_button :design_pattern, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :appropriate_length, 'Was the presentation\'s length appropriate?<br>(1 = Not Appropriate, 10 = Perfectly Appropriate)'.html_safe %>
      <br>
      <%= errors_for(@grade_submission, :appropriate_length) %>
      <% (1..10).to_a.each do |x| %>
        <label for="grade_submission[appropriate_length]" class="radio-inline">
        <%= f.radio_button :appropriate_length, x %>
        <%= x %>
        </label>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :comments, 'Comments on this presentation:' %>
      <%= errors_for(@grade_submission, :comments) %>
      <%= f.text_area :comments, class: 'form-control' %>
    </div>
    <%= submit_tag 'Submit Grade', class: 'btn btn-large btn-primary' %>
  <% end %>
</div>

presentation-grading/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UI/UX Presentations | Professor Groves | CS 170</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">CS 170: UI/UX Presentations</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if @presentations %>
          <form class="navbar-form navbar-left" role="search" action="<%= classroom_path(@classroom) %>" method="get">
            <div class="form-group no-extra-padding">
              <select class="form-control" name="date">
                <% Presentation::DATE_CHOICES.each do |display, value|%>
                  <option value="<%= value %>"><%= display %></option>
                <% end %>
              </select>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% unless notice.blank? %>
    <div class="row">
      <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
        <div class="bg-success padding">
          <%= notice %>
        </div>
      </div>
    </div>
  <% end %>

  <% unless alert.blank? %>
    <div class="row">
      <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
        <div class="bg-danger padding">
          <%= alert %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>